print("Hello, Di")
print('this is a fun project')
print('this is a fun project')
print('this is a fun project')
print('this is a fun project')
print('this is a fun project')
print('this is a fun project')